""" CONFIG """
# DATASET
DATASET_BASEPATH = "./disk"
DATASET_DIRNAME = "imp_csv"
DATASET_CACHE = "dataset_cache"
SAVE_DATASETS = False
INITIAL_TRAINING_PATH = ""
# WINDOWS
NUM_FEATURES = 72
NUM_PREDICTIONS = 6
# JOBS
# -1: means all CPUs, -2: all CPUs but one, -3: all but two...
NJOBS = -3
# MODEL TRAINING
TRAINING_PERCENTAGE_MODELS = 0.25
TRAIN_TEST_RATIO_MODELS = 0.5
ERROR_TYPE_MODELS = "MAPE2"
MODELS_TRAINING = [
    "SHIFT_LR",
    "SHIFT_KNN",
    "SHIFT_RF",
    "SHIFT_SGD",
    "SHIFT_MLP",
    "SHIFT_SVR",
    "CHAIN_LR",
    "CHAIN_KNN",
    "CHAIN_RF",
    "CHAIN_MLP",
    "CHAIN_SVR",
    "CHAIN_SGD",
    "MULTI_LR",
    "MULTI_KNN",
    "MULTI_RF",
    "MULTI_MLP",
    "MULTI_SVR",
    "MULTI_SGD",
]
TRAINING_PATH = "phase1-model-training"
REMOVE_TRAIN_SETS = True
# FFORMA TRAINING
TRAINING_PERCENTAGE_FFORMA = 0.5
TRAIN_TEST_RATIO_FFORMA = 0.5
ERROR_TYPE_FFORMA = "MAPE2"
MODELS_FFORMA = [
    "MULTI_LR",
    "MULTI_KNN",
    "MULTI_RF",
    "MULTI_MLP",
    "MULTI_SVR",
    "MULTI_SGD",
]
FFORMA_PATH = "phase2-fforma-training"
# FFORMA EVALUATION
TRAINING_PERCENTAGE_FFORMA_EVALUATION = 1
TRAIN_TEST_RATIO_FFORMA_EVALUATION = 0
ERROR_TYPE_FFORMA_EVALUATION = "MAPE2"
EVALUATION_PATH = "phase3-fforma-evaluation"
USE_FFORMS = False
